FROM node:18-alpine AS builder
WORKDIR /app
COPY app /app
RUN npm install && npm run build

FROM node:18-alpine AS runtime
WORKDIR /app
RUN npm install -g webserver.local
COPY --from=builder /app/build ./build
EXPOSE 3000
CMD webserver.local -d ./build

